spring.application.name=broker-message-be
server.port=8084

spring.kafka.bootstrap-servers=localhost:9092

# --- Consumer ---
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer


spring.datasource.url=jdbc:postgresql://localhost:5432/retry_jobs_db
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

spring.data.mongodb.uri=mongodb+srv://modelo_prueba_test_admi:8QVlUA1MSVuq9MjZ@cluster0.ovvknir.mongodb.net/product_db

# Estrategia de actualización de tablas
# 'update' es ideal para desarrollo porque crea la tabla de errores si no existe
spring.jpa.hibernate.ddl-auto=update

# Opcional: Para ver en consola qué está haciendo el Job de reintento
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=farcos.soluone@gmail.com
spring.mail.password=oqrm vjzl chmw ibvg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true